---
title: Code of conduct
type: "generic_page"
summary: "Caladown: A Hugo theme and R package by Danielle Navarro"
---

# Code of conduct

The MRP Reading Group is dedicated to providing a harassment-free experience for everyone. We do not tolerate harassment of participants in any form.

This code of conduct applies to all MRP Reading Group spaces, including meetups, Zoom, Twitter, Slack, mailing lists, both online and offline. Anyone who violates this code of conduct may be sanctioned or expelled from these spaces at the discretion of the Organisers.


Harassment includes:

- Offensive comments related to gender, gender identity and expression, sexual orientation, disability, mental illness, neuro(a)typicality, physical appearance, body size, age, race, or religion.
- Unwelcome comments regarding a person's lifestyle choices and practices, including those related to food, health, parenting, drugs, and employment.
- Deliberate misgendering or use of 'dead' or rejected names.
- Gratuitous or off-topic sexual images or behaviour in spaces where they're not appropriate.
- Physical contact and simulated physical contact (eg, textual descriptions like "hug" or "backrub") without consent or after a request to stop.
- Threats of violence.
- Incitement of violence towards any individual, including encouraging a person to commit suicide or to engage in self-harm.
- Deliberate intimidation.
- Stalking or following.
- Harassing photography or recording, including logging online activity for harassment purposes.
- Sustained disruption of discussion.
- Unwelcome sexual attention.
- Pattern of inappropriate social contact, such as requesting/assuming inappropriate levels of intimacy with others.
- Continued one-on-one communication after requests to cease.
- Deliberate "outing" of any aspect of a person's identity without their consent except as necessary to protect vulnerable people from intentional abuse.
- Publication of non-harassing private communication.


# Reporting

If you are being harassed by a member/guest/participant of/at the MRP Reading Group, notice that someone else is being harassed, or have any other concerns, please contact one of the Organizers via email. If the person who is harassing you is an Organizer then you can email Associate Professor Kelly Lyons at the University of Toronto who will handle your incident. We will respond as promptly as we can.


# Consequences

Participants asked to stop any harassing behavior are expected to comply immediately.

If a participant engages in harassing behavior, the Organizers may take any action they deem appropriate, up to and including expulsion from all MRP Reading Group spaces.

This policy is licensed under the Creative Commons Zero license. It is originally from [R Ladies](https://rladies.org/code-of-conduct/) and we thank and acknowledge them for it.
