---
title: Schedule
type: "generic_page"
summary: "Caladown: A Hugo theme and R package by Danielle Navarro"
---

# Upcoming talks


*July 29, 2020*  
**Shiro Kuriwaki** (Harvard University)  
Burris, Kyle C., and Peter D. Hoff, 2020, 'Exact adaptive confidence intervals for small areas', *Journal of Survey Statistics and Methodology*, 8 (2), pp. 206-230.

*August 5, 2020*  
**Jonah Gabry and Mitzi Morris** (Columbia University)  
CommandStan		

*August 12, 2020*  
**Jon Gellar and Erin Lipman** (Mathematica)  
'Insights on MRP from an study on COVID impacts in Africa'

*August 19, 2020*  
**Jyotishka Datta** (University of Arkansas)  
'Shrinkage priors, small area estimation and MRP'

*August 26, 2020*  
TBD

*September 2, 2020*  	
**Elliott Morris** (The Economist)  
Economist model of 2020 election











# Past talks

*July 22, 2020*  
**Lauren Kennedy** (Monash University)  
Considerations of race and ethnicity in MRP

*July 15, 2020*  
**Jennifer Starling** (Mathematica)  
Starling, Jennifer E., Jared S. Murray, Carlos M. Carvalho, Radek K. Bukowski, and James G. Scott, 2020, 'Bart with targeted smoothing: An analysis of patient-specific stillbirth risk', *Annals of Applied Statistics*, 14 (1), pp. 28-50.

*July 8, 2020*  
**Rohan Alexander** (University of Toronto)  
Ghitza, Yair, and Andrew Gelman, 2020, 'Voter Registration Databases and MRP: Toward the Use of Large-Scale Databases in Public Opinion Research', *Political Analysis*, pp. 1-25.

*July 1, 2020*  
**Joseph Ornstein** (Washington University in St Louis)  
Ornstein, Joseph T., 2020, 'Stacked Regression and Poststratification', *Political Analysis*, 28 (2), pp. 293-301.

*June 24, 2020*  
**Yajuan Si** (University of Michigan)  
Robust survey inference with MRP		

*June 17, 2020*  
**Marija Pejcinovska** (University of Toronto)  
Lumley, T. and Scott, A., 2015. AIC and BIC for modeling with complex survey data. *Journal of Survey Statistics and Methodology*, 3 (1), pp. 1-18.


*June 10, 2020*  
Cancelled.

*June 3, 2020*  
**Lauren Kennedy** (Columbia University)  
Prior preditive checks

*May 27, 2020*  
**Ben Skinner** (University of Florida)  
Models for Contingency Tables With Known Margins When Target and Sampled Populations Differ (Bisbee, 2019)

*May 20, 2020*  
**Alex Gao** (University of Toronto)  
Green, D.P. and Kern, H.L., 2012. Modeling heterogeneous treatment effects in survey experiments with Bayesian additive regression trees. *Public opinion quarterly*, 76(3), pp.491-511.

*May 13, 2020*  
**Dan Simpson** (University of Toronto)  
Simpson, D., Rue, H., Riebler, A., Martins, T.G. and Sørbye, S.H., 2017 'Penalising model component complexity: A principled, practical approach to constructing priors' *Statistical science*, 32(1), pp.1-28.

*May 6, 2020*  
**Rohan and Monica Alexander** (University of Toronto)  
Looks or brains? Choosing the optimal set of co-variates to satisfy competing priorities in multi-level regression with post-stratification.

*April 29, 2020*  
**Ben Bales** (Columbia University)  
Downes, M. and Carlin, J.B., 2020. Multilevel regression and poststratification as a modeling approach for estimating population quantities in large population health studies: A simulation study. *Biometrical Journal*, 62(2), pp.479-491.

*April 22, 2020*  
**Mitzi Morris** (Columbia University)  
Using Google Collab with Stan

*April 15, 2020*  
**Lauren Kennedy** (Columbia University)  
All maps of parameter estimates are misleading.

*April 8, 2020*  
**Lauren Kennedy** (Columbia University)  
Kennedy, L. and Gelman, A., 2019. Know your population and know your model: Using model-based regression and poststratification to generalize findings beyond the observed sample. arXiv preprint arXiv:1906.11323.

*March 18, 2020*  
**Lauren Kennedy** (Columbia University)  
Combining survey frames with MRP

*March 11, 2020*  
**Shiro Kuriwaki and Soichiro Yamauchi** (Harvard University)  
Synthetic weighting vs. MRP	(early slides)

*March 4, 2020*  
**Alex Gao** (University of Toronto)  
Gao, Y., Kennedy, L., Simpson, D. and Gelman, A., 2019. Improving multilevel regression and poststratification with structured priors. arXiv preprint arXiv:1908.06716.

*Feb 26, 2020*  
**Jonah Gabry** (Columbia University)  
Demonstration of using Stan.

*Feb 19, 2020*  
**Mitzi Morris** (Columbia University)  
Kastellec, J.P., Lax, J.R., Malecki, M. and Phillips, J.H., 2015. Polarizing the electoral connection: partisan representation in Supreme Court confirmation politics. *The journal of politics*, 77(3), pp.787-804.

*Feb 12, 2020*  
**Rohan Alexander** (University of Toronto)  
Wang, W., Rothschild, D., Goel, S. and Gelman, A., 2015. Forecasting elections with non-representative polls. *International Journal of Forecasting*, 31(3), pp.980-991.

*Feb 5, 2020*  
**Shiro Kuriwaki** (Harvard University)  
Howe, P.D., Mildenberger, M., Marlon, J.R. and Leiserowitz, A., 2015. Geographic variation in opinions on climate change at state and local scales in the USA. *Nature Climate Change*, 5(6), pp.596-603.

*Jan 29, 2020*  
**Alex Gao** (University of Toronto)  
Lax, J.R. and Phillips, J.H., 2009. Gay rights in the states: Public opinion and policy responsiveness. *American Political Science Review*, 103(3), pp.367-386.

*Jan 22, 2020*  
**Shiro Kuriwaki** (Harvard University)  
Fay III, R.E. and Herriot, R.A., 1979. Estimates of income for small places: an application of James-Stein procedures to census data. *Journal of the American Statistical Association*, 74(366a), pp.269-277.

*Jan 8, 2020*  
**Mitzi Morris** (Columbia University)  
Lei, R., Gelman, A. and Ghitza, Y., 2017. The 2008 election: A preregistered replication analysis. *Statistics and Public Policy*, 4(1), pp.1-8.

*December 18, 2019*  
**Rohan Alexander** (University of Toronto)  
Implementing MRP in Stan: Vignette and Walkthrough	

*December 11, 2019*  
**Ben Bales** (Columbia University)  
Gelman, A. and Little, T.C., 1997. Poststratification into many categories using hierarchical logistic regression.

*December 4, 2019*  
**Lauren Kennedy** (Columbia University)  
Gelman, A., 2007. Struggles with survey weighting and regression modeling. *Statistical Science*, 22(2), pp.153-164.
